# Generated by Django 5.1 on 2024-10-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customusermodel',
            table='user',
        ),
    ]
