# Generated by Django 5.1 on 2024-10-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contactusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
