# Generated by Django 5.1 on 2024-11-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tagmodel_articlemodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='categories',
            field=models.ManyToManyField(related_name='articles', to='blog.categorymodel'),
        ),
    ]
