# Generated by Django 5.1 on 2024-11-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_articlemodel_categories'),
        ('blog', '0008_alter_articlemodel_categories'),
    ]

    operations = [
    ]
