# Generated by Django 5.1 on 2024-11-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_commentmodel_user_commentmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='user'),
        ),
    ]
