from .home import home
from .about import AboutView
from .contact_us import contact_us
from .all_articles import AllArticlesView
from .category_blog import category_blog
from .detail_blog import detail_blog
from .comment import CommentFormView
from .create_article import CreateArticleView
from .my_articles import my_articles
from .update_article import UpdateArticleView
from .delete import DeleteArticleView